package com.leo.dal.object;

import java.math.BigDecimal;
import java.util.Date;

public class BHLoanObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.app_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.payment_fund_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String paymentFundId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.status
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.user_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.user_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.id_card
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.phone
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.bank_account
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.bank_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.bank_code
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.amount
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.repayments
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Byte repayments;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.pay_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Date payDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.check_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Date checkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.pay_dead_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Date payDeadDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.is_send
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Byte isSend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.application_site
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String applicationSite;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.living_address
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String livingAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.marriage_status
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Byte marriageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.education
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Byte education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.product_type_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String productTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.create_time
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.update_time
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bh_loan_object.update_by
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    private String updateBy;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.id
     *
     * @return the value of bh_loan_object.id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.id
     *
     * @param id the value for bh_loan_object.id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.app_id
     *
     * @return the value of bh_loan_object.app_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.app_id
     *
     * @param appId the value for bh_loan_object.app_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.payment_fund_id
     *
     * @return the value of bh_loan_object.payment_fund_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getPaymentFundId() {
        return paymentFundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.payment_fund_id
     *
     * @param paymentFundId the value for bh_loan_object.payment_fund_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setPaymentFundId(String paymentFundId) {
        this.paymentFundId = paymentFundId == null ? null : paymentFundId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.status
     *
     * @return the value of bh_loan_object.status
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.status
     *
     * @param status the value for bh_loan_object.status
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.user_id
     *
     * @return the value of bh_loan_object.user_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.user_id
     *
     * @param userId the value for bh_loan_object.user_id
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.user_name
     *
     * @return the value of bh_loan_object.user_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.user_name
     *
     * @param userName the value for bh_loan_object.user_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.id_card
     *
     * @return the value of bh_loan_object.id_card
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.id_card
     *
     * @param idCard the value for bh_loan_object.id_card
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.phone
     *
     * @return the value of bh_loan_object.phone
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.phone
     *
     * @param phone the value for bh_loan_object.phone
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.bank_account
     *
     * @return the value of bh_loan_object.bank_account
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.bank_account
     *
     * @param bankAccount the value for bh_loan_object.bank_account
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount == null ? null : bankAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.bank_name
     *
     * @return the value of bh_loan_object.bank_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.bank_name
     *
     * @param bankName the value for bh_loan_object.bank_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.bank_code
     *
     * @return the value of bh_loan_object.bank_code
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.bank_code
     *
     * @param bankCode the value for bh_loan_object.bank_code
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.amount
     *
     * @return the value of bh_loan_object.amount
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.amount
     *
     * @param amount the value for bh_loan_object.amount
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.repayments
     *
     * @return the value of bh_loan_object.repayments
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Byte getRepayments() {
        return repayments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.repayments
     *
     * @param repayments the value for bh_loan_object.repayments
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setRepayments(Byte repayments) {
        this.repayments = repayments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.pay_date
     *
     * @return the value of bh_loan_object.pay_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Date getPayDate() {
        return payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.pay_date
     *
     * @param payDate the value for bh_loan_object.pay_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setPayDate(Date payDate) {
        this.payDate = payDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.check_date
     *
     * @return the value of bh_loan_object.check_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Date getCheckDate() {
        return checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.check_date
     *
     * @param checkDate the value for bh_loan_object.check_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setCheckDate(Date checkDate) {
        this.checkDate = checkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.pay_dead_date
     *
     * @return the value of bh_loan_object.pay_dead_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Date getPayDeadDate() {
        return payDeadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.pay_dead_date
     *
     * @param payDeadDate the value for bh_loan_object.pay_dead_date
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setPayDeadDate(Date payDeadDate) {
        this.payDeadDate = payDeadDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.is_send
     *
     * @return the value of bh_loan_object.is_send
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Byte getIsSend() {
        return isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.is_send
     *
     * @param isSend the value for bh_loan_object.is_send
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setIsSend(Byte isSend) {
        this.isSend = isSend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.application_site
     *
     * @return the value of bh_loan_object.application_site
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getApplicationSite() {
        return applicationSite;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.application_site
     *
     * @param applicationSite the value for bh_loan_object.application_site
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setApplicationSite(String applicationSite) {
        this.applicationSite = applicationSite == null ? null : applicationSite.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.living_address
     *
     * @return the value of bh_loan_object.living_address
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getLivingAddress() {
        return livingAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.living_address
     *
     * @param livingAddress the value for bh_loan_object.living_address
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setLivingAddress(String livingAddress) {
        this.livingAddress = livingAddress == null ? null : livingAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.marriage_status
     *
     * @return the value of bh_loan_object.marriage_status
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Byte getMarriageStatus() {
        return marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.marriage_status
     *
     * @param marriageStatus the value for bh_loan_object.marriage_status
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setMarriageStatus(Byte marriageStatus) {
        this.marriageStatus = marriageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.education
     *
     * @return the value of bh_loan_object.education
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Byte getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.education
     *
     * @param education the value for bh_loan_object.education
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setEducation(Byte education) {
        this.education = education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.product_type_name
     *
     * @return the value of bh_loan_object.product_type_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getProductTypeName() {
        return productTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.product_type_name
     *
     * @param productTypeName the value for bh_loan_object.product_type_name
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setProductTypeName(String productTypeName) {
        this.productTypeName = productTypeName == null ? null : productTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.create_time
     *
     * @return the value of bh_loan_object.create_time
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.create_time
     *
     * @param createTime the value for bh_loan_object.create_time
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.update_time
     *
     * @return the value of bh_loan_object.update_time
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.update_time
     *
     * @param updateTime the value for bh_loan_object.update_time
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bh_loan_object.update_by
     *
     * @return the value of bh_loan_object.update_by
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bh_loan_object.update_by
     *
     * @param updateBy the value for bh_loan_object.update_by
     *
     * @mbggenerated Tue Jul 11 14:44:44 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }
}