package com.leo.dal.object;

public class HFCompensatoryInfoObject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_compensatory_info_object.id
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_compensatory_info_object.app_id
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    private String appId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hf_compensatory_info_object.date_due
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    private String dateDue;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_compensatory_info_object.id
     *
     * @return the value of hf_compensatory_info_object.id
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_compensatory_info_object.id
     *
     * @param id the value for hf_compensatory_info_object.id
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_compensatory_info_object.app_id
     *
     * @return the value of hf_compensatory_info_object.app_id
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_compensatory_info_object.app_id
     *
     * @param appId the value for hf_compensatory_info_object.app_id
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    public void setAppId(String appId) {
        this.appId = appId == null ? null : appId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hf_compensatory_info_object.date_due
     *
     * @return the value of hf_compensatory_info_object.date_due
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    public String getDateDue() {
        return dateDue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hf_compensatory_info_object.date_due
     *
     * @param dateDue the value for hf_compensatory_info_object.date_due
     *
     * @mbggenerated Tue Apr 11 13:55:33 CST 2017
     */
    public void setDateDue(String dateDue) {
        this.dateDue = dateDue == null ? null : dateDue.trim();
    }
}